<a href="https://colab.research.google.com/github/lhrong16/Data-Science/blob/Week_3/Kaggle3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tutorial 3 (Week 3)**

In [ ]:
# Some tips on coding
# 1. Check for typos - for example the code is 'print' not 'prin'
# 2. Check for space - for example the code is print('hello') not print ('hello')
# 3. Always try to Google for answer - for example 'how to load dataset in Python'

In [ ]:
import pandas as pd #need to download and import csv
from google.colab import files
Data = files.upload()

In [ ]:
import io
df = pd.read_csv('Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.csv')
df.head()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28091 entries, 0 to 28090
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28091 non-null  object
 1   How old are you?                                                                                                                                                                                                                      28091 non-null  object
 2   What industry do you work in?                                                                                                                                                                                                         28017 non-null  object
 3   Job title                                                                                                                                                                                                                             28090 non-null  object
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7267 non-null   object
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28091 non-null  object
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20783 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28091 non-null  object
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        207 non-null    object
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3044 non-null   object
 10  What country do you work in?                                                                                                                                                                                                          28091 non-null  object
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23062 non-null  object
 12  What city do you work in?                                                                                                                                                                                                             28009 non-null  object
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28091 non-null  object
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28091 non-null  object
 15  What is your highest level of education completed?                                                                                                                                                                                    27868 non-null  object
 16  What is your gender?                                                                                                                                                                                                                  27920 non-null  object
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27914 non-null  object
dtypes: float64(1), object(17)
memory usage: 3.9+ MB

In [ ]:
df.isnull().sum()

Timestamp                                                                                                                                                                                                                                   0
How old are you?                                                                                                                                                                                                                            0
What industry do you work in?                                                                                                                                                                                                              74
Job title                                                                                                                                                                                                                                   1
If your job title needs additional context, please clarify here:                                                                                                                                                                        20824
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        0
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                           7308
Please indicate the currency                                                                                                                                                                                                                0
If "Other," please indicate the currency here:                                                                                                                                                                                          27884
If your income needs additional context, please provide it here:                                                                                                                                                                        25047
What country do you work in?                                                                                                                                                                                                                0
If you're in the U.S., what state do you work in?                                                                                                                                                                                        5029
What city do you work in?                                                                                                                                                                                                                  82
How many years of professional work experience do you have overall?                                                                                                                                                                         0
How many years of professional work experience do you have in your field?                                                                                                                                                                   0
What is your highest level of education completed?                                                                                                                                                                                        223
What is your gender?                                                                                                                                                                                                                      171
What is your race? (Choose all that apply.)                                                                                                                                                                                               177
dtype: int64

In [ ]:
df.head(2)

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White

In [ ]:
#Let's focus on 'If your job title needs additional context, please clarify here:' column
# We can select a specific column by using the code df[['column_name']]. Example below
x = df[['If your job title needs additional context, please clarify here:']]
x.head()
#The result takes only one column as below. Lots of NaN/Null values.

  If your job title needs additional context, please clarify here:
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

In [ ]:
# If we want to select a subset of 3 columns we can do df[['column_1','column_2','column_3']]
x = df[['How old are you?','Job title','What country do you work in?']]
x.head()

,How old are you?,Job title,What country do you work in?
0,25-34,Research and Instruction Librarian,United States
1,25-34,Change & Internal Communications Manager,United Kingdom
2,25-34,Marketing Specialist,US
3,25-34,Program Manager,USA
4,25-34,Accounting Manager,US

In [ ]:
# But let's say we want to select a row that meets a certain condition.
# Let's say we want to select those whose salary = 55,000
# We use df[df['column_name']==condition value]
x = df[df["What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)"]=='55,000']
# Here we must be careful, because the datatype for column Salary is 'object' so what ever values in the column can be considered as a string.
# So that is why we wrapped up 55,000 with '' in the command above
x.head()
# Say we want to select those whose salary is below 55,000
# x = df[df['Salary'] <'55,000'] ----we cannot do this because 55,000 is a string, not a number, so cannot do comparison

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
82,4/27/2021 11:04:55,25-34,Nonprofits,Graphic Designer / Webmaster,NaN,"55,000",NaN,USD,NaN,NaN,U.S.,Minnesota,St. Paul,2 - 4 years,2 - 4 years,College degree,Woman,White
133,4/27/2021 11:05:46,55-64,Education (Higher Education),career services professional,NaN,"55,000",NaN,USD,NaN,NaN,United States,NaN,Indianapolis,21 - 30 years,21 - 30 years,Master's degree,Woman,White
188,4/27/2021 11:06:24,25-34,Academic Medicine,Administrative Specialist,lowest level administrator in an academic sect...,"55,000",2500.0,USD,NaN,NaN,USA,Illinois,Chicago,8 - 10 years,5-7 years,College degree,Man,White
212,4/27/2021 11:06:50,35-44,Commercial Real Estate,Administrative Associate,NaN,"55,000",5000.0,USD,NaN,NaN,United States,Texas,Dallas,11 - 20 years,5-7 years,Some college,Woman,White

In [ ]:
#Convert string column to int. This is a little bit advance. Please ignore the 'warnings' etc
df["What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)"] = df["What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)"].replace(',','',regex=True) #this replace the comma ',' in 55,000 to 55000
df["What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)"] = df["What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)"].astype(int) # this convert the column datatypes from object into numbers , in this case integer
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28091 entries, 0 to 28090
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28091 non-null  object
 1   How old are you?                                                                                                                                                                                                                      28091 non-null  object
 2   What industry do you work in?                                                                                                                                                                                                         28017 non-null  object
 3   Job title                                                                                                                                                                                                                             28090 non-null  object
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7267 non-null   object
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28091 non-null  int64
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20783 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28091 non-null  object
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        207 non-null    object
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3044 non-null   object
 10  What country do you work in?                                                                                                                                                                                                          28091 non-null  object
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23062 non-null  object
 12  What city do you work in?                                                                                                                                                                                                             28009 non-null  object
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28091 non-null  object
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28091 non-null  object
 15  What is your highest level of education completed?                                                                                                                                                                                    27868 non-null  object
 16  What is your gender?                                                                                                                                                                                                                  27920 non-null  object
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27914 non-null  object
dtypes: float64(1), int64(1), object(16)
memory usage: 3.9+ MB

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

In [ ]:
#Now only can we select those with salary less than 50000
x = df[df["What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)"] < 50000] #no need quotation marks anymore, because Salary column is a column of number
x.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
6,4/27/2021 11:02:51,25-34,Publishing,Publishing Assistant,NaN,33000,2000.0,USD,NaN,NaN,USA,South Carolina,Columbia,2 - 4 years,2 - 4 years,College degree,Woman,White
9,4/27/2021 11:03:02,35-44,"Accounting, Banking & Finance",Senior Accountant,NaN,45000,0.0,USD,NaN,I work for a Charter School,United States,Florida,Palm Coast,21 - 30 years,21 - 30 years,College degree,Woman,"Hispanic, Latino, or Spanish origin, White"
10,4/27/2021 11:03:03,25-34,Nonprofits,Office Manager,NaN,47500,0.0,USD,NaN,NaN,United States,NaN,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
14,4/27/2021 11:03:11,18-24,Health care,Patient care coordinator,NaN,32000,NaN,CAD,NaN,NaN,Canada,NaN,Remote,1 year or less,1 year or less,College degree,Woman,White

In [ ]:
# Back to the question, which column, which row has null values?
# We know the column 'If your job title needs additional context, please clarify here:' has NaN values
x = df['Context'] # we assign the column 'Context' from the dataframe df to variable